org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true

neogradle.subsystems.conventions.runs.create-default-run-per-type=false

mod.group=at.minecraftschurli.mods
mod.id=potionbundles
mod.version=1.8
mod.name=Potion Bundles
mod.vendor=MinecraftschurliMods
mod.authors=IchHabeHunger54, Minecraftschurli
mod.description=Potions can now be bound into bundles, to save inventory space.
mod.url=https://www.curseforge.com/minecraft/mc-mods/potion-bundles

java_version=25

github.owner=MinecraftschurliMods
github.repo=PotionBundles

license.name=GPLv3
license.url=https://www.gnu.org/licenses/gpl-3.0.en.html
license.file=LICENSE

mc_version=26.1
mc_version_range=[26.1,26.2)

neo_version=26.1.0.5-beta
neo_version_range=[26.1.0.1-beta,26.2)

dependency.jei.version=29.2.0.17
dependency.jei.version.range=[29.1,30)

loader.version=[4,)

mc-publish.curseforge=382836
mc-publish.modrinth=ZZLWU8jS
