modLoader="javafml"
loaderVersion = "${loader_version_range}"
license="GPLv3"
[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_name}"
displayURL="${mod_url}"
authors = "${mod_author}"
description='''
Three potions can now be bound into bundles, to save inventory space.
'''
[[dependencies.${mod_id}]]
modId="forge"
versionRange="${forge_version_range}"
mandatory=true
ordering="NONE"
side="BOTH"
[[dependencies.${mod_id}]]
modId="minecraft"
versionRange="${mc_version_range}"
mandatory=true
ordering="NONE"
side="BOTH"
