modLoader="javafml"
loaderVersion = "${loader_version_range}"
license="GPLv3"
[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="${mod_url}"
authors = "${mod_authors}"
description='''${mod_description}'''
[[dependencies.${mod_id}]]
modId="forge"
versionRange="${forge_version_range}"
mandatory=true
ordering="NONE"
side="BOTH"
[[dependencies.${mod_id}]]
modId="minecraft"
versionRange="${mc_version_range}"
mandatory=true
ordering="NONE"
side="BOTH"
